apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "name" . }}-certs-job
  annotations:
    helm.sh/hook-weight: "5"
    helm.sh/hook: "post-install,post-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation"
spec:
  backoffLimit: 1
  template:
    metadata:
      name: {{ template "name" . }}-certs-job
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: {{ template "name" . }}-certs-job
      restartPolicy: Never
      volumes:
        - name: {{ template "name" . }}-tls-cert
          secret:
            secretName: {{ template "name" . }}-tls-cert
            optional: true
      containers:
        - name: certificates
          image: {{ .Values.job.image.repository }}:{{ .Values.job.image.tag }}
          securityContext:
{{- toYaml .Values.securityContext | nindent 12 }}
          command:
            - bash
            - -c
            - |
{{ tpl (.Files.Get "files/certificates.sh" | printf "%s" | indent 14) . }}