apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-ssl
  namespace: {{ .Release.Namespace }}
  {{ if .Values.global.certificates.gardener }}
  annotations:
    dns.gardener.cloud/class: "garden"
    dns.gardener.cloud/dnsnames: 'apiserver.'{{ trimPrefix "*." .Values.global.domainName }}'
  {{ end }}
spec:
  {{ if .Values.global.isLocalEnv }}
  type: NodePort
  {{ else }}
  type: LoadBalancer
  {{ end }}
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: {{ .Values.port.secure }}
  selector:
    app: {{ template "name" . }}
