---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "certificates.name" . }}-legacy
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: "before-hook-creation"
    "helm.sh/hook": "post-install, post-upgrade"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kube-system
  name: {{ template "certificates.name" . }}-kube-system-legacy
  annotations:
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: "before-hook-creation"
    "helm.sh/hook": "post-install, post-upgrade"
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ['coredns']
    verbs: ["patch"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kyma-system
  name: {{ template "certificates.name" . }}-kyma-system-legacy
  annotations:
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: "before-hook-creation"
    "helm.sh/hook": "post-install, post-upgrade"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: istio-system
  name: {{ template "certificates.name" . }}-istio-system-legacy
  annotations:
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: "before-hook-creation"
    "helm.sh/hook": "post-install, post-upgrade"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "certificates.name" . }}-legacy
  namespace: kube-system
  annotations:
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: "before-hook-creation"
    "helm.sh/hook": "post-install, post-upgrade"
subjects:
  - kind: ServiceAccount
    name: {{ template "certificates.name" . }}-legacy
    namespace: {{.Release.Namespace}}
roleRef:
  kind: Role
  name: {{ template "certificates.name" . }}-kube-system-legacy
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "certificates.name" . }}-legacy
  namespace: kyma-system
  annotations:
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: "before-hook-creation"
    "helm.sh/hook": "post-install, post-upgrade"
subjects:
  - kind: ServiceAccount
    name: {{ template "certificates.name" . }}-legacy
    namespace: {{.Release.Namespace}}
roleRef:
  kind: Role
  name: {{ template "certificates.name" . }}-kyma-system-legacy
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "certificates.name" . }}-legacy
  namespace: istio-system
  annotations:
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: "before-hook-creation"
    "helm.sh/hook": "post-install, post-upgrade"
subjects:
  - kind: ServiceAccount
    name: {{ template "certificates.name" . }}-legacy
    namespace: {{.Release.Namespace}}
roleRef:
  kind: Role
  name: {{ template "certificates.name" . }}-istio-system-legacy
  apiGroup: rbac.authorization.k8s.io