configmapName: oidc-ca
nameOverride: apiserver-proxy

port:
  secure: 9443
  insecure: 8444
  metrics: 2112

job:
  image:
    repository: eu.gcr.io/kyma-project/incubator/develop/k8s-tools
    tag: "20210113-12c4e3b5"

podSecurityPolicy:
  enabled: true

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  privileged: false
  runAsGroup: 65534
  runAsNonRoot: true
  runAsUser: 65534
global:
  certificates:
    gardener: false
