apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: certificaterequests.applicationconnector.kyma-project.io
spec:
  group: applicationconnector.kyma-project.io

  names:
    kind: CertificateRequest
    singular: certificaterequest
    plural: certificaterequests
  scope: Cluster
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                csrInfoUrl:
                  type: string
              required:
                - csrInfoUrl
              type: object

