apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: clusterserviceplans.servicecatalog.k8s.io
  labels:
    svcat: "true"
spec:
  group: servicecatalog.k8s.io
  versions:
  - name: v1beta1
    storage: true
    served: true
    additionalPrinterColumns:
      - name: External-Name
        type: string
        jsonPath: .spec.externalName
      - name: Broker
        type: string
        jsonPath: .spec.clusterServiceBrokerName
      - name: Class
        type: string
        jsonPath: .spec.clusterServiceClassRef.name
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
    subresources:
      status: {}
  scope: Cluster
  names:
    plural: clusterserviceplans
    singular: clusterserviceplan
    kind: ClusterServicePlan
    # categories is a list of grouped resources the custom resource belongs to.
    categories:
      - all
      - svcat
