apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: eventactivations.applicationconnector.kyma-project.io
  annotations:
    "helm.sh/resource-policy": keep
spec:
  group: applicationconnector.kyma-project.io
  scope: Namespaced
  names:
    plural: eventactivations
    singular: eventactivation
    kind: EventActivation
    shortNames:
      - ea
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                sourceId:
                  type: string
                  minLength: 1
                  maxLength: 253
                  pattern: '^[a-zA-Z0-9]([-a-zA-Z0-9]*[a-zA-Z0-9])?(\.[a-zA-Z0-9]([-a-zA-Z0-9]*[a-zA-Z0-9])?)*$'
                displayName:
                  type: string
