apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podpresets.settings.svcat.k8s.io
  annotations:
    "helm.sh/resource-policy": keep
    "api-approved.kubernetes.io": "https://github.com/kyma-project/kyma/pull/11197"
spec:
  group: settings.svcat.k8s.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                env:
                  items:
                    type: object
                  type: array
                envFrom:
                  items:
                    type: object
                  type: array
                selector:
                  type: object
                volumeMounts:
                  items:
                    type: object
                  type: array
                volumes:
                  items:
                    type: object
                  type: array
              required:
              - selector
              type: object
            status:
              type: object
          type: object
  names:
    kind: PodPreset
    plural: podpresets
  scope: Namespaced
