job:
  image:
    repository: eu.gcr.io/kyma-project/incubator/develop/k8s-tools
    tag: "20210113-12c4e3b5"

certificate:
  kyma:
    name: kyma-gateway-certs
    namespace: istio-system
  apiserverProxy:
    name: apiserver-proxy-tls-cert
    namespace: kyma-system

userProvided:
  issuer:
    name: kyma-ca-issuer
    configMap:
      name: kyma-ca-issuer
      namespace: kyma-installer

global:
  certificates:
    selfSigned: false
